### ISSUE TITLE
Can this be used with other 3D software?

### ISSUE THREAD

**Issue by delebash** [nkeeline/OpenPose-to-Blender-Facial-Capture-Transfer#1]
Programs like Reallusions [iClone ](https://www.reallusion.com/iclone/)or [Daz 3D](https://www.daz3d.com/)?

**Comment by nkeeline** [comment]
It cannot, I have written Daz3D javascript and if you wrote a plugin for that I'm sure it would work, but I had to fix the bones on the daz3d genesis 8 character for my script to work on a daz character in blender so it would be some work to get an unmodified gen8 rig to work natively in daz.

**Comment by delebash** [comment]
Got it.  Thanks
