### ISSUE TITLE
Feature Request:  Live from webcam

### ISSUE THREAD

**Issue by delebash** [nkeeline/OpenPose-to-Blender-Facial-Capture-Transfer#2]
Would be awesome if we could run this in blender live from a webcam.

This project is fantastic.  I have looked at several others [openface](https://github.com/TadasBaltrusaitis/OpenFace) but it outputs the files in FACS Action Unit Format

[FACSvatar](https://github.com/NumesSanguis/FACSvatar) can do live webcam but for windows you have to setup docker and it only works with models created from [MBLAB ](https://mb-lab-community.github.io/MB-Lab.github.io/).  While with your program you have outlined how easy it is just to map to your model bones,

Thank you so much for this program and also the excellent instructional video.  This project was very easy to setup on Windows 10

Thanks!!!!!
Dan

**Comment by nkeeline** [comment]
Glad you liked it:)

**Comment by delebash** [comment]
Thanks!
