### ISSUE TITLE
Openpose cpu vs gpu performance fps comparison

### ISSUE THREAD

**Issue by delebash** [nkeeline/OpenPose-to-Blender-Facial-Capture-Transfer#3]
Just some info:
My system:
Intel core i9 9900k
Memory 32 GB
Graphics card Nvidia RTX 2070 Super

With the cpu version I get about .4 fps.  Is this about right with the setup I have?

With gpu I get about 10fps which I find acceptable.

Thanks!
Dan

**Comment by nkeeline** [comment]
Glad it worked for you... your numbers seem quite right.  I get .1 fps on my i7-5820k.  Yours is obviously newer and better than mine:)
