### ISSUE TITLE
Blender model info

### ISSUE THREAD

**Issue by riebling** [nkeeline/OpenPose-to-Blender-Facial-Capture-Transfer#4]
This is awesome, and amazing, and unfortunately apparently unusable for someone not already in the possession of a Blender 3d model with rigging/bones/armature/control-points, and the savvy to map their names and locations to the code and OpenPose 2d face and 3d body data.

Is the model used a custom creation, or are there any standard humanoid Blender models with rigging, or is this all a black art that has to be created by wizards with existing expertise? It seems magical at first, then the magic is revealed, then there's a black box filled with more magic in the form of a pre-existing rigged Blender model of unknown origin. Perhaps Video 0 has that information, elsewhere :)

Still, top notch, love this, love the on-camera charisma and instant appeal, super grateful for excellent presentation, working example code, and results!

**Comment by nkeeline** [comment]
Sorry, the model was purchased from DAZ3D so I couldn't post it.  I am sorry it's so complicated.   I was frustrated by a lack of advanced tutorials on blender.  Andrew Price, cg geek and others have cornered the market on noob tutorials and there are several out there on how to rig a character.  If you wanted to rig your own you only need to create bones like I show in the second tutorial and then weight map them to the face.  I suppose I could create a rig and post it from makehuman or something.... hmmm.  Thanks for the kind words.

**Comment by riebling** [comment]
Dude, thanks for the info, yes, as it turns out the real good models will cost you real money :)
3d character animation is quite more complicated than I'd expected, as a quick-and-dirty prototyper with a mind to being able to piece anything together with anything somewhat quickly thanks to the help of computers. With Blender, that quickly became something else, i.e. a 53 step guide to rigging a character, and the 47 Blender tutorial videos just to learn the interface. Whoa
